Repository laminas/laminas-continuous-integration-action, pull requests merged in 2022-01, with the labels that each got.

#71 Lock dependencies and reduce final docker image size (fixes `markdownlint` CI runs)
  .dockerignore
  Dockerfile
  setup/markdownlint/dummy-ko-markdown-test-file.md
  setup/markdownlint/dummy-ok-markdown-test-file.md
  setup/markdownlint/markdownlint.json
  setup/markdownlint/package-lock.json
  setup/markdownlint/package.json
  setup/markdownlint/problem-matcher.json
  setup/markdownlint/setup.sh
  setup/php/5.6/dependencies
  setup/php/5.6/setup.sh
  setup/php/7.0/dependencies
  setup/php/7.0/setup.sh
  setup/php/7.1/dependencies
  setup/php/7.1/setup.sh
  setup/php/7.2/dependencies
  setup/php/7.2/setup.sh
  setup/php/7.3/dependencies
  setup/php/7.3/setup.sh
  setup/php/7.4/dependencies
  setup/php/7.4/setup.sh
  setup/php/8.0/dependencies
  setup/php/8.0/setup.sh
  setup/php/8.1/dependencies
  setup/php/8.1/setup.sh
  setup/phpunit/problem-matcher.json
  setup/staabm-annotate-pull-request-from-checkstyle/composer.json
  setup/staabm-annotate-pull-request-from-checkstyle/composer.lock
  setup/ubuntu/dependencies
  setup/ubuntu/setup.sh
Labels: Bug, Enhancement

#74 Fix markdown configuration path
  Dockerfile
Labels: Bug

#76 Simplify docker build and push workflow
  .github/workflows/build-and-push-containers.yml
Labels: Enhancement
